## numpy library


In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
#creating a 2d array
a2=np.array([[1,2,3,4],[2,3,4,5]])
print(a2)

[[1 2 3 4]
 [2 3 4 5]]


In [5]:
#creating a 3d array
a3=np.array([[[1,2,3,4],[1,2,3,4]],[[5,6,7,8],[8,8,9,0]]])
print(a3)

[[[1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [8 8 9 0]]]


In [6]:
# shape= no. of rows and colums 
print(a2.shape)

(2, 4)


In [7]:
#ndim= dimension of array
print(a2.ndim)

2


In [8]:
#dtype=data typ[es of elemenets in array
print(a2.dtype)

int64


In [9]:
#arange= to inserts elements 
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.random.randint(1,11,size=(2,3))

array([[2, 5, 6],
       [8, 5, 8]], dtype=int32)

In [13]:
x=np.array([[7,2,3],
            [2,5,2],
            [3,5,3]
            ])
y =np.array([[1,8,3],
             [2,5,2],
             [5,7,8]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 3]]
[[1 8 3]
 [2 5 2]
 [5 7 8]]


In [14]:
print (x@y)#matrix multiplication

[[26 87 49]
 [22 55 32]
 [28 70 43]]


In [15]:
np.dot(x,y)#matrix multiplication


array([[26, 87, 49],
       [22, 55, 32],
       [28, 70, 43]])

In [16]:
#prod is the shortcut for product multiply the elements in one matrix

x.prod()

np.int64(37800)

In [17]:
x.mean()#mean of all elements

np.float64(3.5555555555555554)

In [18]:
y.mean()

np.float64(4.555555555555555)

In [19]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 3]]


In [20]:
x.mean(axis=0)#column wise mean

array([4.        , 4.        , 2.66666667])

In [21]:
x.mean(axis=1)#row wise mean

array([4.        , 3.        , 3.66666667])

In [22]:
print(x.sum())
print(x.std())
print(x.var())

32
1.640535895581489
2.6913580246913584


In [23]:
a= np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))#1st quartile
print(np.percentile(a,50))#median
print(np.percentile(a,75))#3rd quartile

3.0
5.0
7.0


In [24]:
b=np.random.randint(11,100,(4,4))
print(b)

[[48 72 34 62]
 [43 11 62 81]
 [94 87 14 25]
 [52 93 78 69]]


In [25]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[48 72 34 62 43 11 62 81]
 [94 87 14 25 52 93 78 69]]
8X2
[[48 72]
 [34 62]
 [43 11]
 [62 81]
 [94 87]
 [14 25]
 [52 93]
 [78 69]]


In [26]:
x=np.random.randint(1,11,(5,5))
print(x)

[[ 2  8 10  5  7]
 [10  6  9  3  9]
 [ 7  4  6 10  9]
 [ 4  3  8  1  4]
 [10  2  8  1  8]]


In [27]:
print(x[0])#1st row
print(x[0,1])#1st row and secon d coloumn first element
print(x[-1])

print(x[:3])
print(x[3:])

[ 2  8 10  5  7]
8
[10  2  8  1  8]
[[ 2  8 10  5  7]
 [10  6  9  3  9]
 [ 7  4  6 10  9]]
[[ 4  3  8  1  4]
 [10  2  8  1  8]]
